name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

env:
  # in the future, this flag will not be needed
  CODEQL_EXTRACTOR_JAVA_RUN_ANNOTATION_PROCESSORS: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]

    steps:
    - uses: actions/checkout@v2

    # WebGoat requires Java/JDK 17
    - name: Set up JDK 17
      if: matrix.language == 'java'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        # [optional] enabled extended queries
        # queries: +security-extended,security-and-quality
        # [optional] Field Config - standard packs, extensions, and extra packs
        config-file: advanced-security/codeql-queries/config/codeql.yml@main

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # Run the Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # Submit Maven Dependency Tree to GitHub
    - name: Maven Dependency Tree Dependency Submission
      if: matrix.language == 'java'
      uses: advanced-security/maven-dependency-submission-action@v3.0.2
